parameters:
    env(DB_HOST): '127.0.0.1'
    env(DB_DRIVER): 'mysql'
    env(DB_USER): 'user'
    env(DB_PASSWORD): 'user'
    env(DB_PORT): '3306'
    env(DB_NAME): 'elasticms'
    env(DB_CONNECTION_TIMEOUT): 30

doctrine:
    dbal:
        url: '%env(string:DB_DRIVER)%://%env(string:DB_USER)%:%env(urlencode:DB_PASSWORD)%@%env(string:DB_HOST)%:%env(string:DB_PORT)%/%env(string:DB_NAME)%'
        options:
            2: '%env(int:DB_CONNECTION_TIMEOUT)%' #const PDO:ATTR_TIMEOUT = 2 , minimum value is 2 https://pracucci.com/php-pdo-pgsql-connection-timeout.html
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
