parameters:
    env(DB_HOST): '127.0.0.1'
    env(DB_DRIVER): 'mysql'
    env(DB_USER): 'user'
    env(DB_PASSWORD): 'user'
    env(DB_PORT): '3306'
    env(DB_NAME): 'elasticms'

doctrine:
    dbal:
        url: '%env(string:DB_DRIVER)%://%env(string:DB_USER)%:%env(urlencode:DB_PASSWORD)%@%env(string:DB_HOST)%:%env(string:DB_PORT)%/%env(string:DB_NAME)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
