parameters:
    env(DEFAULT_LOCAL): 'en'
    env(ELASTICMS_PATH): '%kernel.project_dir%/vendor/elasticms'

framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(DEFAULT_LOCAL)%'

    session:
        handler_id: ~
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: strict

    esi: true
    fragments: true
    php_errors:
        log: true

    validation:
        email_validation_mode: html5

    http_method_override: false
    handle_all_throwables: true
when@redis:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

when@test:
    framework:
        test: true
        session:
            storage_id: session.storage.mock_file
