parameters:
    env(DEFAULT_LOCAL): 'en'

framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(DEFAULT_LOCAL)%'

    session:
        handler_id: ~
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true
    php_errors:
        log: true

    validation:
        email_validation_mode: html5

when@redis:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

when@test:
    framework:
        test: true
        session:
            storage_id: session.storage.mock_file