parameters:
    env(DEFAULT_LOCAL): 'en'
    env(ELASTICMS_PATH): '%kernel.project_dir%/vendor/elasticms'

framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(DEFAULT_LOCAL)%'

    session:
        handler_id: ~
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true
    php_errors:
        log: true

    validation:
        email_validation_mode: html5

    http_client:
      default_options:
        headers:
          'Cookie': 'XDEBUG_SESSION=PHPSTORM'

when@redis:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler

when@db:
    framework:
        session:
            handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

when@store_data:
    framework:
        session:
            handler_id: ems_common.store_data_session_handler

when@test:
    framework:
        test: true
        session:
            storage_id: session.storage.mock_file
