parameters:
    env(LOG_OUTPUT): 'php://stdout'

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%env(resolve:LOG_OUTPUT)%'
                level: debug
                channels: ["!event", "!elastica"]
            console:
                type:   console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            flash:
                type: service
                id: ems_core.core_ui.flash_message_logger
                channels: [ app,core,audit ]
            doctrine:
                type: service
                id: ems_common.monolog.doctrine
                channels: [ app,core,audit ]

when@prod: &monolog_prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine" ]
            flash:
                type: service
                id: ems_core.core_ui.flash_message_logger
                channels: [ app,core,audit ]
            doctrine:
                type: service
                id: ems_common.monolog.doctrine
                channels: [ app,core,audit ]

when@redis: *monolog_prod
when@db: *monolog_prod
when@store_data: *monolog_prod

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
