# This configuration file is autogenerated by the container startup script

map $request_uri {{ $.Env.SYMFONY_SCRIPT_NAME_NGINX_VARIABLE_NAME }} {
    default "/index.php";

{{- range (datasource "aliases") }}
{{- $a := strings.TrimSuffix "/" . | strings.TrimPrefix "/" }}
    ~^/{{ $a }}/ "/{{ $a }}/index.php";
{{- end -}}

}
