# This configuration file is autogenerated by the container startup script

{{- if ne $.Env.NGINX_X_FRAME_OPTIONS "" }}
add_header X-Frame-Options "{{ $.Env.NGINX_X_FRAME_OPTIONS }}" always;
{{- end }}

{{- if ne $.Env.NGINX_X_CONTENT_TYPE_OPTIONS "" }}
add_header X-Content-Type-Options "{{ $.Env.NGINX_X_CONTENT_TYPE_OPTIONS }}" always;
{{- end }}

{{- if ne $.Env.NGINX_REFERRER_POLICY "" }}
add_header Referrer-Policy "{{ $.Env.NGINX_REFERRER_POLICY }}" always;
{{- end }}

{{- if ne $.Env.NGINX_PERMISSIONS_POLICY "" }}
add_header Permissions-Policy "{{ $.Env.NGINX_PERMISSIONS_POLICY }}" always;
{{- end }}

{{- if ne $.Env.NGINX_CONTENT_SECURITY_POLICY "" }}
add_header Content-Security-Policy "{{ $.Env.NGINX_CONTENT_SECURITY_POLICY }}" always;
{{- end }}

{{- if ne $.Env.NGINX_STRICT_TRANSPORT_SECURITY "" }}
add_header Strict-Transport-Security "{{ $.Env.NGINX_STRICT_TRANSPORT_SECURITY }}" always;
{{- end }}

{{- if ne $.Env.NGINX_X_XSS_PROTECTION "" }}
add_header X-XSS-Protection "{{ $.Env.NGINX_X_XSS_PROTECTION }}" always;
{{- end }}
