#!/usr/bin/env bash
# This script is autogenerated by the container startup script
#
# Runs once a minute. When there is nothing to do, ems:job:run still prints a
# dozen lines, so its output is shown only when it fails, or under DEBUG. A
# job's own output is kept with the job, in the admin.

output=$(/opt/sbin/{{ .Env.ELASTICMS_INSTANCE_NAME }} ems:job:run ${JOBS_OPTS} 2>&1)
status=$?

if [ "$status" -ne 0 ] || [ "${DEBUG,,}" = true ]; then
    echo "ems:job:run for [ {{ .Env.ELASTICMS_INSTANCE_NAME }} ] exited with status $status" >&2
    echo "$output" >&2
fi

exit "$status"
