#!/usr/bin/env bash
# This script is autogenerated by the container startup script

set -o allexport
source {{ .Env.APP_CONFIG_DIR }}/{{ .Env.ELASTICMS_INSTANCE_NAME }}
set +o allexport

if [ ${1:-list} = sql ] ; then

  if [ ${DB_DRIVER:-mysql} = mysql ] ; then
    if [ ${1:-list} = sql ] ; then
      mysql --port=$DB_PORT --host=$DB_HOST --user=$DB_USER --password=$(urlencode.py $DB_PASSWORD) $DB_NAME
    fi;
  elif [ ${DB_DRIVER:-mysql} = pgsql ] ; then
    if [ ${1:-list} = sql ] ; then
      psql postgresql://${DB_USER}:$(urlencode.py $DB_PASSWORD)@${DB_HOST//,/:${DB_PORT},}:${DB_PORT}/${DB_NAME}?connect_timeout=${DB_CONNECTION_TIMEOUT:-30} ${@:2}
    fi;
  else
    echo Driver $DB_DRIVER not supported
  fi;
else
  export EMS_PROCESS_COMMAND={{ .Env.ELASTICMS_INSTANCE_NAME }}
  php -d memory_limit=${CLI_PHP_MEMORY_LIMIT:-512M} {{ .Env.APP_SRC_DIR }}/bin/console "$@"
fi;
