#!/usr/bin/env bash
# This script is autogenerated by the container startup script
set -o allexport
source {{ .Env.APP_CONFIG_DIR }}/{{ .Env.ELASTICMS_INSTANCE_NAME }}
set +o allexport

shutdown_handler() {
    /opt/sbin/{{ .Env.ELASTICMS_INSTANCE_NAME }}-messenger-consume-shutdown || true
    kill -TERM "$child_pid" 2>/dev/null
}

child_pid=0

trap shutdown_handler SIGTERM SIGINT SIGQUIT

export EMS_PROCESS_COMMAND={{ .Env.ELASTICMS_INSTANCE_NAME }}

php {{ .Env.APP_SRC_DIR }}/bin/console messenger:consume async {{ .Env.MESSENGER_CONSUME_COMMAND_OPTS }} &

child_pid=$!
wait "$child_pid"
