# This VirtualHost is autogenerated by the container startup script

server {

    listen 9090 default_server;

    server_name _;

    location /metrics {
      access_log off;
      vhost_traffic_status_bypass_stats on;
      vhost_traffic_status_display;
      vhost_traffic_status_display_format prometheus;
    }

    location /vts-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;
      vhost_traffic_status_display;
      vhost_traffic_status_display_format html;
    }

    location = /stub-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;
      allow 127.0.0.1;
      allow all;
      deny all;
      stub_status;
    }

    location ~ ^/(status|ping)$ {
      access_log off;
      allow 127.0.0.1;
      allow all;
      deny all;

      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

      fastcgi_pass unix:/app/var/run/php-fpm/php-fpm.sock;
    }

}