# This VirtualHost is autogenerated by the container startup script

server {

    listen 9090 default_server;

    server_name {{ $.Env.METRICS_VHOST_SERVER_NAME }} _;

    # The monitoring ACL of base-php: MONITORING_ALLOW, the local socket, and a
    # 403 for anyone else. The allow list this replaces had no final deny, so
    # nginx let every other network through.
    if ($monitoring_forbidden) { return 403; }

    location /metrics {
      access_log off;
      vhost_traffic_status_bypass_stats on;


      vhost_traffic_status_display;
      vhost_traffic_status_display_format prometheus;
    }

    location /vts-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;


      vhost_traffic_status_display;
      vhost_traffic_status_display_format html;
    }

    location = /stub-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;


      stub_status;
    }

    location ~ ^/(status|ping)$ {
      access_log off;


      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

      fastcgi_pass unix:/app/var/run/php-fpm/php-fpm.sock;
    }

    include conf.d/metrics/*.conf;

    # This server exposes monitoring endpoints and nothing else.
    location / {
      access_log off;
      return 404;
    }

}