# This VirtualHost is autogenerated by the container startup script

server {

    listen 9090 default_server;

    server_name {{ $.Env.METRICS_VHOST_SERVER_NAME }} _;

    location /metrics {
      access_log off;
      vhost_traffic_status_bypass_stats on;

      include conf.d/default.metrics-permissions.conf;

      vhost_traffic_status_display;
      vhost_traffic_status_display_format prometheus;
    }

    location /vts-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;

      include conf.d/default.metrics-permissions.conf;

      vhost_traffic_status_display;
      vhost_traffic_status_display_format html;
    }

    location = /stub-status {
      access_log off;
      vhost_traffic_status_bypass_stats on;

      include conf.d/default.metrics-permissions.conf;

      stub_status;
    }

    location ~ ^/(status|ping)$ {
      access_log off;

      include conf.d/default.metrics-permissions.conf;

      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

      fastcgi_pass unix:/app/var/run/php-fpm/php-fpm.sock;
    }

    include conf.d/metrics/*.conf;

}