# This VirtualHost is autogenerated by the container startup script

server {

    listen {{ $.Env.EMS_METRIC_PORT }} default_server;

    server_name _;

    root {{ $.Env.NGINX_PUBLIC_DIR }};

    index index.php;

    # ============================================================
    # BUNDLES ASSETS (bundles Symfony)
    # ============================================================

    location ^~ /bundles/ {
        try_files $uri =404;
    }

    # ============================================================
    # ROOT Symfony
    # ============================================================

    location / {
        try_files $uri /index.php$is_args$args;
    }

    # ============================================================
    # PHP-FPM
    # ============================================================

    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/app/var/run/php-fpm/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        include fastcgi_params;
        include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Prevents URIs that include the front controller. This will 404:
        # http://example.com/index.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }

    # ============================================================
    # BLOCKING
    # ============================================================

    location ~ \.php$ {
        return 404;
    }

}