# This VirtualHost is autogenerated by the container startup script

include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.symfony-script-name.map;

server {

    listen 9000;

    server_name {{ $.Env.NGINX_SERVER_NAME }};

    root {{ $.Env.NGINX_PUBLIC_DIR }};

    index index.php;

    # Redirects nginx builds itself -- a directory without its trailing slash --
    # carried the internal host and port: /bundles answered
    # "Location: http://<host>:9000/bundles/", which a browser behind the
    # proxy cannot reach. A relative Location keeps the address it came in on.
    absolute_redirect off;

    # base-php's soft throttling (NGINX_SOFT_THROTTLE_*). The zones are declared
    # for the whole of nginx but only act where a server includes this file; the
    # instance vhosts never did, so they were never throttled. Empty while
    # throttling is off.
    include /opt/etc/nginx/conf.d/throttling-server.conf;

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.security-headers.conf;

    # ============================================================
    # BUNDLES ASSETS (bundles Symfony)
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.assets.conf;

    # ============================================================
    # ROOT Symfony
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.symfony.conf;

    # ============================================================
    # PHP-FPM
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.php-fpm.conf;

    # ============================================================
    # BLOCKING
    # ============================================================

    location ~ \.php$ {

{{- if ne $.Env.NGINX_DEBUG_ENABLED "false" }}
        set $debug_nginx_location "star.php";
        set $debug_nginx_uri "$uri";
        add_header X-Debug-Nginx-Uri "$debug_nginx_uri" always;
        add_header X-Debug-Nginx-Symfony-Location "$debug_nginx_location" always;
{{- end }}

        return 404;
    }

{{ if ne $.Env.NGINX_DENY_LOCATION_REGEXP "" }}
    location ~ {{ $.Env.NGINX_DENY_LOCATION_REGEXP }} {
        deny all;
    }
{{- end }}

}