# This VirtualHost is autogenerated by the container startup script

server {

{{- if ne $.Env.METRICS_DEFAULT_SERVER "false" }}
    listen {{ $.Env.EMS_METRIC_PORT }} default_server;
    server_name {{ $.Env.SERVER_NAME }} _;
{{- else }}
    listen {{ $.Env.EMS_METRIC_PORT }};
    server_name {{ $.Env.SERVER_NAME }};
{{- end }}

    root {{ $.Env.NGINX_PUBLIC_DIR }};

    index index.php;

    # ============================================================
    # ROOT Symfony
    # ============================================================

    location /metrics {
        try_files $uri /index.php$is_args$args;
    }

    # ============================================================
    # PHP-FPM
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.php-fpm.conf;

    # ============================================================
    # BLOCKING
    # ============================================================

    location ~ \.php$ {

{{- if ne $.Env.DEBUG "false" }}
        set $debug_nginx_location "star.php";
        set $debug_nginx_uri "$uri";
        add_header X-Debug-Nginx-Uri "$debug_nginx_uri" always;
        add_header X-Debug-Nginx-Symfony-Location "$debug_nginx_location" always;
{{- end }}

        return 404;
    }

}