# This VirtualHost is autogenerated by the container startup script

include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.symfony-script-name.map;

server {

    listen 9000;

    server_name {{ $.Env.SERVER_NAME }};

    root {{ $.Env.NGINX_PUBLIC_DIR }};

    index index.php;

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.security-headers.conf;

    # ============================================================
    # BUNDLES ASSETS (bundles Symfony)
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.assets.conf;

    # ============================================================
    # ROOT Symfony
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.symfony.conf;

    # ============================================================
    # PHP-FPM
    # ============================================================

    include conf.d/{{ $.Env.ELASTICMS_INSTANCE_NAME }}.php-fpm.conf;

    # ============================================================
    # BLOCKING
    # ============================================================

    location ~ \.php$ {

{{- if ne $.Env.DEBUG "false" }}
        set $debug_nginx_location "star.php";
        set $debug_nginx_uri "$uri";
        add_header X-Debug-Nginx-Uri "$debug_nginx_uri" always;
        add_header X-Debug-Nginx-Symfony-Location "$debug_nginx_location" always;
{{- end }}

        return 404;
    }

{{ if ne $.Env.NGINX_DENY_LOCATION_REGEXP "" }}
    location ~ {{ $.Env.NGINX_DENY_LOCATION_REGEXP }} {
        deny all;
    }
{{- end }}

}