monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        flash:
            type: service
            id: ems_core.core_ui.flash_message_logger
            channels: [app]
        doctrine:
            type: service
            id: ems_common.monolog.doctrine
            channels: [app]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
