# This VirtualHost is autogenerated by the container startup script
<VirtualHost *:9000>
    ServerName {{ .Env.SERVER_NAME }}

{{- if ne .Env.SERVER_ALIASES "" }}
    ServerAlias {{ .Env.SERVER_ALIASES }}
{{- end }}

    LimitRequestLine 16384

    # Uncomment the following line to force Apache to pass the Authorization
    # header to PHP: required for "basic_auth" under PHP-FPM and FastCGI
    #
    # SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=\$1

    # For Apache 2.4.9 or higher
    # Using SetHandler avoids issues with using ProxyPassMatch in combination
    # with mod_rewrite or mod_autoindex
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/app/var/run/php-fpm/php-fpm.sock|fcgi://localhost/"
    </FilesMatch>

    DocumentRoot {{ .Env.APACHE_PUBLIC_DIR }}
    <Directory {{ .Env.APACHE_PUBLIC_DIR }} >
        AllowOverride None
        Order Allow,Deny
        Allow from All
        Require all granted
        FallbackResource /index.php
    </Directory>

    Header always append X-Frame-Options {{ .Env.APACHE_X_FRAME_OPTIONS }}
    Header always append X-XSS-Protection {{ .Env.APACHE_X_XSS_PROTECTION }}
    Header always append X-Content-Type-Options {{ .Env.APACHE_X_CONTENT_TYPE_OPTIONS }}

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

{{- if ne .Env.ALIAS "" }}
    Alias {{ .Env.ALIAS }} {{ .Env.APACHE_PUBLIC_DIR }}

    RewriteCond %{REQUEST_URI} ^{{ .Env.ALIAS }}/(.+)$
    RewriteCond {{ .Env.APACHE_PUBLIC_DIR }}/%1 -f [OR]
    RewriteCond {{ .Env.APACHE_PUBLIC_DIR }}/%1 -d
    RewriteRule ^ - [L]

    RewriteCond %{REQUEST_URI} !^{{ .Env.ALIAS }}/index.php
    RewriteRule ^{{ .Env.ALIAS }} {{ .Env.ALIAS }}/index.php$1 [PT,L,QSA]
{{- end }}

    IncludeOptional /opt/etc/apache2/sites-enabled/{{ .Env.ELASTICMS_INSTANCE_NAME }}-app.env

</VirtualHost>