# This VirtualHost is autogenerated by the container startup script

Listen {{ .Env.EMS_METRIC_PORT }}

<VirtualHost *:9090>
    ServerName {{ .Env.METRICS_VHOST_SERVER_NAME }}
    ServerAlias *
    LimitRequestLine 16384

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/app/var/run/php-fpm/php-fpm.sock|fcgi://localhost/"
    </FilesMatch>

    DocumentRoot {{ .Env.APACHE_PUBLIC_DIR }}
    <Directory {{ .Env.APACHE_PUBLIC_DIR }} >
        AllowOverride None
        Order Allow,Deny
        Allow from All
        Require all granted
        FallbackResource /index.php
    </Directory>

    <Directory {{ .Env.APACHE_ASSETS_DIR }} >
        FallbackResource disabled
    </Directory>

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    IncludeOptional /opt/etc/apache2/conf.d/__metrics.env

</VirtualHost>