emsco:
    resource: '@EMSCoreBundle/config/routing/all.php'

probe:
    resource: '@EMSCommonBundle/config/routing/probe.php'

ems_common:
    resource: 'ems_common.route.loader::load'
    type: service

emsch_routes:
    resource: 'emsch.routing.route_loader'
    type: service

forms:
    resource: '@EMSFormBundle/config/routing/form.php'
    prefix: /emsf

forms_debug:
    resource: '@EMSFormBundle/config/routing/debug.php'
    prefix: /emsf

assets:
    resource: '@EMSCommonBundle/config/routing/assets.php'
