security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_AUTHOR:          ROLE_USER
        ROLE_REVIEWER:        ROLE_AUTHOR
        ROLE_TRADUCTOR:       ROLE_REVIEWER
        ROLE_PUBLISHER:       ROLE_TRADUCTOR
        ROLE_WEBMASTER:       ROLE_PUBLISHER
        ROLE_ADMIN:           ROLE_WEBMASTER
        ROLE_SUPER_ADMIN:     ROLE_ADMIN

    providers:
        api_key_user_provider:
            id: api_key_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
        main:
            anonymous: ~
            provider: fos_userbundle
            form_login:
                use_forward: true
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                provider: fos_userbundle
                dn_string: '{username}@smals-mvm'
            logout:
                path: /logout
                target: /login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            switch_user: { role: ROLE_ADMIN, provider:   fos_userbundle }
            
    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/health_check(\.json)?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth-token$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public-key$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/go-to-login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/status.json$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/status$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/documentation$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/data/file, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/i18n-type, roles: ROLE_ADMIN }
        - { path: ^/wysiwyg-profile, roles: ROLE_ADMIN }
        - { path: ^/content-type, roles: ROLE_ADMIN }
        - { path: ^/environment, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/elasticsearch/delete-search, roles: ROLE_USER }
        - { path: ^/elasticsearch, roles: ROLE_ADMIN }
        - { path: ^/publisher/align, roles: ROLE_PUBLISHER }
        - { path: ^/, roles: ROLE_USER }
