fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
ems_core:
    resource: "@EMSCoreBundle/Controller/"
    type:     annotation
ems_local_user:
    resource: "@EMSLocalUserBundle/Controller/"
    type:     annotation
