monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        ems:
            type: service
            id: ems_common.monolog.ems_handler
            channels: [app, php]
        flash:
            type: service
            id: ems_common.monolog.flash_handler
            channels: [app]
        nested:
            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
            path: "php://stderr"
            level: notice
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
